src/LesAutres/SiteBundle/Entity/Event.php
<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="events")
 * @ORM\Entity(repositoryClass="LesAutres\SiteBundle\Entity\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    protected $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    protected $link;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="Show", inversedBy="events")
     * @ORM\JoinColumn(name="show_id", referencedColumnName="id")
     */
    protected $show;

    /**
     * @ORM\ManyToOne(targetEntity="Place", inversedBy="events")
     * @ORM\JoinColumn(name="place_id", referencedColumnName="id")
     */
    protected $place;

    /**
     * @ORM\OneToMany(targetEntity="Date", mappedBy="event", cascade={"persist", "remove"})
     */
    protected $dates;
    
    
    
    
    
    
    /**
     * CONSTRUCTOR
     */

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->dates = new ArrayCollection();
    }
    
    public function __toString()
    {
        return (
            $this->id ?
            ($this->title ? $this->title : "Événement ".$this->id) :
            "Nouvel événement"
        );
    }
    
    
    
    
    
    
    /**
     * METHODS
     */
    
    public function setDates($dates) {
        $this->dates = new ArrayCollection();
 
        foreach ($dates as $date) {
            $date->setEvent($this);
            $this->addDate($date);
        }
    }
    
    public function getDatesAfterNow() {
        $dates_after_now = new ArrayCollection();
        $now = new \DateTime();
        
        foreach ($this->dates as $date) {
            if ($date->getDate() > $now) {
                $dates_after_now[] = $date;
            }
        }
        
        return $dates_after_now;
    }
    
    
    
    
    
    
    /**
     * GETTERS & SETTERS
     */

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Event
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Event
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set show
     *
     * @param \LesAutres\SiteBundle\Entity\Show $show
     * @return Event
     */
    public function setShow(\LesAutres\SiteBundle\Entity\Show $show = null)
    {
        $this->show = $show;
    
        return $this;
    }

    /**
     * Get show
     *
     * @return \LesAutres\SiteBundle\Entity\Show 
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Set place
     *
     * @param \LesAutres\SiteBundle\Entity\Place $place
     * @return Event
     */
    public function setPlace(\LesAutres\SiteBundle\Entity\Place $place = null)
    {
        $this->place = $place;
    
        return $this;
    }

    /**
     * Get place
     *
     * @return \LesAutres\SiteBundle\Entity\Place 
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Add dates
     *
     * @param \LesAutres\SiteBundle\Entity\Date $dates
     * @return Event
     */
    public function addDate(\LesAutres\SiteBundle\Entity\Date $dates)
    {
        $this->dates[] = $dates;
    
        return $this;
    }

    /**
     * Remove dates
     *
     * @param \LesAutres\SiteBundle\Entity\Date $dates
     */
    public function removeDate(\LesAutres\SiteBundle\Entity\Date $dates)
    {
        $this->dates->removeElement($dates);
    }

    /**
     * Get dates
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getDates()
    {
        return $this->dates;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Event
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Event
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set link
     *
     * @param string $link
     * @return Event
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string 
     */
    public function getLink()
    {
        return $this->link;
    }
}

src/LesAutres/SiteBundle/Entity/File.php
<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM; 
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="files")
 * @ORM\Entity(repositoryClass="LesAutres\SiteBundle\Entity\FileRepository")
 */
class File
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;

    /**
     * @ORM\Column(name="is_pdf", type="boolean")
     */
    private $isPdf;

    /**
     * @ORM\Column(name="is_image", type="boolean")
     */
    private $isImage;

    /**
     * @ORM\Column(type="string", length=32, nullable=true)
     * image width and height
     */
    protected $attr;

    /**
     * @ORM\ManyToOne(targetEntity="Show", inversedBy="files")
     * @ORM\JoinColumn(name="show_id", referencedColumnName="id")
     */
    protected $show;

    /**
     * @ORM\Column(type="string", length=255, name="mimetype", nullable=true)
     */
    protected $mimeType;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;
    
    protected $file;
    
    
    
    
    
    
    /**
     * CONSTRUCTOR
     */

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
    }
    
    public function __toString()
    {
        return (
            $this->path ?
            $this->path :
            "Nouveau fichier"
        );
    }
    
    
    
    
    
    
    /**
     * METHODS
     */
    
    public function isImage()
    {
        return ($this->mimeType == "image/jpeg" || $this->mimeType == "image/jpg" || $this->mimeType == "image/png");
    }
    
    public function generateThumbnail()
    {
        if($this->isImage())
        {
            global $kernel;
            
            if ('AppCache' == get_class($kernel)) {
                $kernel = $kernel->getKernel();
            }
            
            $kernel->getContainer()->get('image.handling')
                ->open($this->getAbsolutePath())
                ->zoomCrop(150, 225)
                ->save($this->getThumbnailAbsolutePath())
            ;
        }
    }
    
    
    
    
    
    
    /**
     * FILE UPLOAD
     */
    
    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->file) {
            return;
        }
        
        $this->mimeType = $this->file->getMimeType();
        
        // width and height
        if($this->isImage())
        {
            list($width, $height, $type, $attr) = getimagesize($this->file);
            $this->attr = $attr;
        }

        // use the original file name here but you should
        // sanitize it at least to avoid any security issues
        $filename = $this->file->getClientOriginalName();

        // move takes the target directory and then the
        // target filename to move to
        $this->file->move(
            $this->getUploadRootDir(),
            $filename
        );

        // set the path property to the filename where you've saved the file
        $this->path = $filename;

        // clean up the file property as you won't need it anymore
        $this->file = null;
        
        // generate thumbnail
        if($this->isImage())
        {
            $this->generateThumbnail();
        }
    }
    
    public function getAbsolutePath()
    {
        return $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return '/'.$this->getUploadDir().'/'.$this->path;
    }
    
    public function getThumbnailAbsolutePath()
    {
        return $this->getUploadRootDir().'/thumbnail/'.$this->path;
    }

    public function getThumbnailWebPath()
    {
        return '/'.$this->getUploadDir().'/thumbnail/'.$this->path;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/show/'.$this->show->getSlug();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }
    
    
    
    
    
    
    /**
     * GETTERS & SETTERS
     */

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return File
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set mimeType
     *
     * @param string $mimeType
     * @return File
     */
    public function setMimeType($mimeType)
    {
        $this->mimeType = $mimeType;
    
        return $this;
    }

    /**
     * Get mimeType
     *
     * @return string 
     */
    public function getMimeType()
    {
        return $this->mimeType;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return File
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return File
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set show
     *
     * @param \LesAutres\SiteBundle\Entity\Show $show
     * @return File
     */
    public function setShow(\LesAutres\SiteBundle\Entity\Show $show = null)
    {
        $this->show = $show;
    
        return $this;
    }

    /**
     * Get show
     *
     * @return \LesAutres\SiteBundle\Entity\Show 
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Set file
     *
     * @param File $file
     * @return Project
     */
    public function setFile($file)
    {
        $this->file = $file;
    
        return $this;
    }

    /**
     * Get file
     *
     * @return File
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Set isPdf
     *
     * @param boolean $isPdf
     * @return File
     */
    public function setIsPdf($isPdf)
    {
        $this->isPdf = $isPdf;
    
        return $this;
    }

    /**
     * Get isPdf
     *
     * @return boolean 
     */
    public function getIsPdf()
    {
        return $this->isPdf;
    }

    /**
     * Set isImage
     *
     * @param boolean $isImage
     * @return File
     */
    public function setIsImage($isImage)
    {
        $this->isImage = $isImage;
    
        return $this;
    }

    /**
     * Get isImage
     *
     * @return boolean 
     */
    public function getIsImage()
    {
        return $this->isImage;
    }

    /**
     * Set attr
     *
     * @param string $attr
     * @return File
     */
    public function setAttr($attr)
    {
        $this->attr = $attr;
    
        return $this;
    }

    /**
     * Get attr
     *
     * @return string 
     */
    public function getAttr()
    {
        return $this->attr;
    }
}

src/LesAutres/SiteBundle/Controller/BrowseController.php
<?php

namespace LesAutres\SiteBundle\Controller;

use LesAutres\SiteBundle\Controller\DefaultController;
use LesAutres\SiteBundle\Entity\Date;
use LesAutres\SiteBundle\Entity\Page;
use LesAutres\SiteBundle\Entity\Show;
use Symfony\Component\HttpFoundation\Response;

class BrowseController extends DefaultController
{
    public function indexAction()
    {
        return $this->render(
            'LesAutresSiteBundle:Browse:index.html.twig',
            array(
                'title' => "Accueil",
                'description' => "Compagnie de théâtre professionnelle basée en Provence. Elle est spécialisée en théâtre-forum, théâtre-image et théâtre de l'opprimé. Ses membres sont comédiens, techniciens et auteurs de spectacle vivant.",
                'keywords' => "compagnie, compagnie des autres, théâtre, théâtre forum, ateliers, formation, création, professionnel, spectacles",
                'menu_underline_slug' => "accueil",
            )
        );
    }
    
    
    
    public function pageAction(Page $page)
    {
        $shows = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Show')
            ->getShowsForPage($page)
        ;
        
        return $this->render(
            'LesAutresSiteBundle:Browse:page.html.twig',
            array(
                'title' => $page->getTitle(),
                'description' => $page->getSummary(),
                'keywords' => $page->getKeywords(),
                'menu_underline_slug' => $page->getSlug(),
                'page' => $page,
                'shows' => $shows,
            )
        );
    }
    
    
    
    public function showAction(Show $show)
    {
        $pdf = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:File')
            ->findOneBy(array(
                'show' => $show,
                'isPdf' => true,
            ))
        ;
        
        $image = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:File')
            ->findOneBy(array(
                'show' => $show,
                'isImage' => true,
            ))
        ;
        
        return $this->render(
            'LesAutresSiteBundle:Browse:show.html.twig',
            array(
                'title' => $show->getTitle(),
                'description' => $show->getSummary(),
                'keywords' => $show->getKeywords(),
                'menu_underline_slug' => $show->getPage()->getSlug(),
                'show' => $show,
                'pdf' => $pdf,
                'image' => $image,
            )
        );
    }
}

src/LesAutres/SiteBundle/Resources/views/Browse/date.html.twig
{% extends 'LesAutresSiteBundle::layout.html.twig' %}

{% block content %}
    <h1>{{ title }}</h1>
    {% for date in dates %}
        {% if date.event and date.event.show %}
            {{ include('LesAutresSiteBundle:Default:event.html.twig', {'event': date.event}) }}
        {% endif %}
    {% endfor %}
{% endblock %}

src/LesAutres/SiteBundle/Resources/views/Browse/index.html.twig
{% extends 'LesAutresSiteBundle::layout.html.twig' %}

{% block content %}
    <h1>la Compagnie des Autres</h1>
    <div class="frame">
        <p>
            <span class="bold">Théâtre forum</span><br/>
            Créée en 1990, la Compagnie des Autres est composée de comédiens, auteurs, techniciens et metteurs en scène professionnels. A côté de créations “classiques”, elle développe depuis plusieurs années sa pratique d’un théâtre citoyen et engagé auprès des spectateurs, le théâtre-forum.<br/>
            <a class="show_link" href="{{ path('page', {'slug': 'theatre-forum'}) }}">Lire la suite</a>
        </p>
        <div class="clear"></div>
    </div>
    <div class="frame">
        <p>
            <span class="bold">Création à la carte</span><br/>
            La Compagnie des Autres intervient à la demande dans le cadre de la création de spectacles sur des thèmes choisis, adaptés à un public ciblé ou très large.<br/>
            <a class="show_link" href="{{ path('page', {'slug': 'creation-a-la-carte'}) }}">Lire la suite</a>
        </p>
        <div class="clear"></div>
    </div>
    <div class="frame">
        <p>
            <span class="bold">Ateliers et formations</span><br/>
            La Compagnie des Autres intervient à la demande dans le cadre d’opérations à court , moyen et long terme, pour la formation de formateurs, la sensibilisation des publics, la mise en place d’ateliers périodiques et la création de spectacles d'amateurs sur des thèmes choisis.<br/>
            <a class="show_link" href="{{ path('page', {'slug': 'ateliers-et-formations'}) }}">Lire la suite</a>
        </p>
        <div class="clear"></div>
    </div>
    <div class="frame">
        <p>
            <span class="bold">Autres spectacles</span><br/>
            Chaque année depuis sa création, la Compagnie des Autres participe à la création et la diffusion d'un spectacle de théâtre conventionnel, en production, coproduction ou coréalisation. Ces spectacles sont disponibles à la vente.<br/>
            <a class="show_link" href="{{ path('page', {'slug': 'autres-spectacles'}) }}">Lire la suite</a>
        </p>
        <div class="clear"></div>
    </div>
{% endblock %}

src/LesAutres/SiteBundle/Resources/views/Browse/page.html.twig
{% extends 'LesAutresSiteBundle::layout.html.twig' %}

{% block content %}
    <h1>{{ title }}</h1>
    {{ include('LesAutresSiteBundle:Default:social.html.twig', {'url': app.request.scheme ~ '://' ~ app.request.httpHost ~ path('page', {'slug': page.slug})}) }}
    {{ page.text|raw }}
    {% if count(shows) > 0 %}
        {% for show in shows %}
            {{ include('LesAutresSiteBundle:Default:show.html.twig', {'show': show}) }}
        {% endfor %}
    {% else %}
        {{ include('LesAutresSiteBundle:Default:social.html.twig', {'url': app.request.scheme ~ '://' ~ app.request.httpHost ~ path('page', {'slug': page.slug})}) }}
    {% endif %}
{% endblock %}

src/LesAutres/SiteBundle/Resources/views/Browse/show.html.twig
{% extends 'LesAutresSiteBundle::layout.html.twig' %}

{% block content %}
    <div class="show_infos">
        {% if image %}<a href="{{ image.webPath }}" target="_blank"><img src="{{ image.thumbnailWebPath }}" width="150" height="225" alt="Illustration {{ show.title }}" class="picture" /></a><br/>{% endif %}
        {% if pdf %}<div class="center"><a href="{{ pdf.webPath }}" class="dossier" title="Dossier PDF"><img width="16" height="16" src="/images/icons/pdf.png" alt="Dossier PDF" />&nbsp;&nbsp;&nbsp;Dossier</a></div>{% endif %}
    </div>
    <h1>{{ title }}</h1>
    {{ include('LesAutresSiteBundle:Default:social.html.twig', {'url': app.request.scheme ~ '://' ~ app.request.httpHost ~ path('show', {'slug': show.slug})}) }}
    {% if show.summary %}<h3>{{ show.summary }}</h3>{% endif %}
    {% if show.duration or show.actorCount or show.masterCount or show.playletCount %}
        <ul>
            {% if show.duration %}<li>Durée : {{ show.duration }}</li>{% endif %}
            {% if show.actorCount %}<li>{{ show.actorCount }} comédien{% if show.actorCount > 1 %}s{% endif %}</li>{% endif %}
            {% if show.masterCount %}<li>{{ show.masterCount }} meneur{% if show.masterCount > 1 %}s{% endif %} de jeu</li>{% endif %}
            {% if show.playletCount %}<li>{{ show.playletCount }} saynète{% if show.playletCount > 1 %}s{% endif %}</li>{% endif %}
        </ul>
    {% endif %}
    {{ show.text|raw }}
    {% if count(show.events) >= 1 %}
        <h2>Prochaines représentations</h2>
        {% for event in show.events %}
            {% if count(event.datesAfterNow) > 0 %}
                {{ include('LesAutresSiteBundle:Default:event.html.twig', {'event': event}) }}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}