src/LesAutres/SiteBundle/Entity/Date.php
<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="dates")
 * @ORM\Entity(repositoryClass="LesAutres\SiteBundle\Entity\DateRepository")
 */
class Date
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $date;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="Event", inversedBy="dates")
     * @ORM\JoinColumn(name="event_id", referencedColumnName="id")
     */
    protected $event;
    
    
    
    
    
    
    /**
     * CONSTRUCTOR
     */

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->date = new \DateTime();
        $this->date->setTime(0, 0, 0);
    }
    
    public function __toString()
    {
        return $this->getFormatedDateTime(true);
    }
    
    
    
    
    
    
    /**
     * METHODS
     */
    
    /**
     * Retourne la date et l'heure formatées en français
     * 
     * @param boolean $dayofweek
     * @return string
     */
    public function getFormatedDateTime($dayofweek = true)
    {
        return $this->getFormatedDate($dayofweek).($this->getFormatedTime() === "00h00" ? "" : " à ".$this->getFormatedTime());
    }
    
    /**
     * Retourne la date formatée en français
     * 
     * @param boolean $dayofweek
     * @return string
     */
    public function getFormatedDate($dayofweek = true)
    {
        $timestamp = $this->date->getTimestamp();
        
        $daysofweek = array(
            1 => "lundi",
            2 => "mardi",
            3 => "mercredi",
            4 => "jeudi",
            5 => "vendredi",
            6 => "samedi",
            7 => "dimanche",
        );
        
        $months = array(
            1 => "janvier",
            2 => "février",
            3 => "mars",
            4 => "avril",
            5 => "mai",
            6 => "juin",
            7 => "juillet",
            8 => "août",
            9 => "septembre",
            10 => "octobre",
            11 => "novembre",
            12 => "décembre",
        );
        
        return
            ($dayofweek ? $daysofweek[date('N', $timestamp)]." " : '').
            date('j', $timestamp).(date('j', $timestamp) == 1 ? "er" : '')." ".
            $months[date('n', $timestamp)]." ".
            date('Y', $timestamp)
        ;
    }
    
    /**
     * Retourne l'heure formatée en français
     * 
     * @param boolean $seconds
     * @return string
     */
    public function getFormatedTime()
    {
        return date('H\hi', $this->date->getTimestamp());
    }
    
    
    
    
    
    
    /**
     * GETTERS & SETTERS
     */

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Date
     */
    public function setDate($date)
    {
        $this->date = $date;
    
        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Date
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Date
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set event
     *
     * @param \LesAutres\SiteBundle\Entity\Event $event
     * @return Date
     */
    public function setEvent(\LesAutres\SiteBundle\Entity\Event $event = null)
    {
        $this->event = $event;
    
        return $this;
    }

    /**
     * Get event
     *
     * @return \LesAutres\SiteBundle\Entity\Event 
     */
    public function getEvent()
    {
        return $this->event;
    }
}

src/LesAutres/SiteBundle/Entity/Event.php
<?php

namespace LesAutres\SiteBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="events")
 * @ORM\Entity(repositoryClass="LesAutres\SiteBundle\Entity\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    protected $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    protected $link;

    /**
     * @ORM\Column(type="datetime", name="created_at")
     */
    protected $createdAt;

    /**
     * @ORM\Column(type="datetime", name="updated_at")
     */
    protected $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity="Show", inversedBy="events")
     * @ORM\JoinColumn(name="show_id", referencedColumnName="id")
     */
    protected $show;

    /**
     * @ORM\ManyToOne(targetEntity="Place", inversedBy="events")
     * @ORM\JoinColumn(name="place_id", referencedColumnName="id")
     */
    protected $place;

    /**
     * @ORM\OneToMany(targetEntity="Date", mappedBy="event", cascade={"persist", "remove"})
     */
    protected $dates;
    
    
    
    
    
    
    /**
     * CONSTRUCTOR
     */

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->updatedAt = new \DateTime();
        $this->dates = new ArrayCollection();
    }
    
    public function __toString()
    {
        return (
            $this->id ?
            ($this->title ? $this->title : "Événement ".$this->id) :
            "Nouvel événement"
        );
    }
    
    
    
    
    
    
    /**
     * METHODS
     */
    
    public function setDates($dates) {
        $this->dates = new ArrayCollection();
 
        foreach ($dates as $date) {
            $date->setEvent($this);
            $this->addDate($date);
        }
    }
    
    public function getDatesAfterNow() {
        $dates_after_now = new ArrayCollection();
        $now = new \DateTime();
        
        foreach ($this->dates as $date) {
            if ($date->getDate() > $now) {
                $dates_after_now[] = $date;
            }
        }
        
        return $dates_after_now;
    }
    
    
    
    
    
    
    /**
     * GETTERS & SETTERS
     */

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Event
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Event
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set show
     *
     * @param \LesAutres\SiteBundle\Entity\Show $show
     * @return Event
     */
    public function setShow(\LesAutres\SiteBundle\Entity\Show $show = null)
    {
        $this->show = $show;
    
        return $this;
    }

    /**
     * Get show
     *
     * @return \LesAutres\SiteBundle\Entity\Show 
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * Set place
     *
     * @param \LesAutres\SiteBundle\Entity\Place $place
     * @return Event
     */
    public function setPlace(\LesAutres\SiteBundle\Entity\Place $place = null)
    {
        $this->place = $place;
    
        return $this;
    }

    /**
     * Get place
     *
     * @return \LesAutres\SiteBundle\Entity\Place 
     */
    public function getPlace()
    {
        return $this->place;
    }

    /**
     * Add dates
     *
     * @param \LesAutres\SiteBundle\Entity\Date $dates
     * @return Event
     */
    public function addDate(\LesAutres\SiteBundle\Entity\Date $dates)
    {
        $this->dates[] = $dates;
    
        return $this;
    }

    /**
     * Remove dates
     *
     * @param \LesAutres\SiteBundle\Entity\Date $dates
     */
    public function removeDate(\LesAutres\SiteBundle\Entity\Date $dates)
    {
        $this->dates->removeElement($dates);
    }

    /**
     * Get dates
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getDates()
    {
        return $this->dates;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Event
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Event
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set link
     *
     * @param string $link
     * @return Event
     */
    public function setLink($link)
    {
        $this->link = $link;

        return $this;
    }

    /**
     * Get link
     *
     * @return string 
     */
    public function getLink()
    {
        return $this->link;
    }
}

src/LesAutres/SiteBundle/Controller/DefaultController.php
<?php

namespace LesAutres\SiteBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    public function nextEventsAction()
    {
        $dates = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Date')
            ->getNextDates(50)
        ;
        
        return $this->render(
            'LesAutresSiteBundle:Default:next_events.html.twig',
            array(
                'dates' => $dates,
            )
        );
    }
    
    
    
    public function menuAction($menu_underline_slug)
    {
        $pages = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Page')
            ->findAll()
        ;
        
        return $this->render(
            'LesAutresSiteBundle:Default:menu.html.twig',
            array(
                'pages' => $pages,
                'menu_underline_slug' => $menu_underline_slug,
            )
        );
    }
    
    
    
    public function slideshowAction($page_slug)
    {
        if(!$page_slug)
        {
            $page_slug = 'accueil';
        }
        
        $images_web_dir = '/images/slideshow/'.$page_slug;
        $images_root_dir = __DIR__.'/../Resources/public'.$images_web_dir;
        if(!file_exists($images_root_dir))
        {
            return $this->render('LesAutresSiteBundle:Default:empty.html.twig');
        }
        
        $images = array();
        if ($handle = opendir($images_root_dir))
        {
            while (false !== ($file = readdir($handle)))
            {
                if ($file != "." && $file != ".." && !is_dir($file))
                {
                    $images[] = $file;
                }
            }
            closedir($handle);
        }
        sort($images);
        
        return $this->render(
            'LesAutresSiteBundle:Default:slideshow.html.twig',
            array(
                'web_dir' => $images_web_dir,
                'images' => $images,
            )
        );
    }
    
    
    
    public function scrollingTextAction()
    {
        $option = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Setting')
            ->findOneBy(array('key' => 'scrolling_text'))
        ;
        
        $scrolling_text = $option->getValue();
        
        return $this->render(
            'LesAutresSiteBundle:Default:string.html.twig',
            array(
                'string' => $scrolling_text,
            )
        );
    }
    
    
    
    public function sitemapAction()
    {
        // pages statiques
        $urls = array(
            "http://www.lesautres.org/",
            "http://www.lesautres.org/nous-contacter",
        );
        
        // pages
        $pages = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Page')
            ->findAll()
        ;
        foreach($pages as $page)
        {
            $urls[] = "http://www.lesautres.org/".$page->getSlug();
        }
        
        // fiches spectacles
        $shows = $this->getDoctrine()
            ->getRepository('LesAutresSiteBundle:Show')
            ->findAll()
        ;
        foreach($shows as $show)
        {
            $urls[] = "http://www.lesautres.org/spectacle/".$show->getSlug();
        }
        
        // réponse
        $response = new Response();
        $response->headers->set('Content-Type', 'text/xml');
        $response->sendHeaders();
        
        return $this->render(
            'LesAutresSiteBundle:Default:sitemap.xml.twig',
            array(
                'urls' => $urls,
            ),
            $response
        );
    }
}

src/LesAutres/SiteBundle/Resources/views/Default/event.html.twig
<div class="frame" itemscope itemtype="http://schema.org/TheaterEvent">
    <div class="place">
        <div class="googlemaps">
            <a href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=fr&amp;q={{ event.place.street|replace({' ': '%20'}) }},%20{{ event.place.zipcode }}%20{{ event.place.city|replace({' ': '%20'}) }},%20France&amp;ie=UTF8&amp;z=14&amp;t=m&amp;iwloc=near" target="_blank">
                <img src="http://staticmap.openstreetmap.de/staticmap.php?center={{ event.place.latitude }},{{ event.place.longitude }}&zoom={{ event.place.zoom }}&size=200x200&markers={{ event.place.latitude }},{{ event.place.longitude }},ol-marker-blue" alt="Carte" width="200" height="200" /><br/>
                Afficher le plan
            </a>
        </div>
    </div>
    <div class="date">
        <p itemprop="location" itemscope itemtype="http://schema.org/PostalAddress">
            <span itemprop="name" class="bold">{{ event.place }}</span><br/>
            <span itemprop="streetAddress">{{ event.place.street }}</span><br/>
            <span itemprop="postalCode">{{ event.place.zipcode }}</span>
            <span itemprop="addressLocality">{{ event.place.city }}</span>
            <span itemprop="addressCountry" class="hidden">France</span>
        </p>
        {% if event.title or event.description %}
            <p>
                {% if event.title %}<span itemprop="name" class="bold">{{ event.title }}</span><br/>{% endif %}
                {% if event.description %}<span itemprop="description">{{ event.description }}</span>{% endif %}
            </p>
        {% endif %}
        <ul>
            {% for date in event.datesAfterNow %}
                <li>{{ date }}<span itemprop="startDate" class="hidden">{{ date.date.format(constant('DATE_ISO8601')) }}</span></li>
            {% endfor %}
        </ul>
    </div>
    <div class="clear"></div>
</div>

src/LesAutres/SiteBundle/Resources/views/Default/menu.html.twig
<ul class="menu">
    <li>
        <a href="{{ path('homepage') }}" {% if menu_underline_slug == 'accueil' %} class="underline"{% endif %}>Accueil</a>
    </li>
    {% for page in pages %}
        <li>
            <a href="{{ path('page', {'slug': page.slug}) }}" {% if page.slug == menu_underline_slug %} class="underline"{% endif %}>{{ page.title }}</a>
        </li>
    {% endfor %}
</ul>

src/LesAutres/SiteBundle/Resources/views/Default/next_events.html.twig
{% set lastdate = '' %}
{% for date in dates %}
    {% if not (lastdate == date.formatedDate(false)) %}
        <h4>{{ date.formatedDate(false) }}</h4>
    {% endif %}
    {% if date.event %}
        <p>
            {% if not (date.formatedTime == '00h00') %}{{ date.formatedTime }} - {% endif %}
            {% if date.event.show %}
                <a href="{{ path('show', {'slug': date.event.show.slug}) }}">
                    {{ date.event.show.title }}
                </a>
            {% else %}
                {% if date.event.link %}<a href="{{ date.event.link }}" target="_blank">{% endif %}
                    {{ date.event.title }}
                {% if date.event.link %}</a>{% endif %}
                {% if date.event.description %}<br/>{{ date.event.description }}{% endif %}
            {% endif %}
            <br />{{ date.event.place.name }}, {{ date.event.place.city }}
        </p>
    {% endif %}
    {% set lastdate = date.formatedDate(false) %}
{% endfor %}

src/LesAutres/SiteBundle/Resources/views/Default/show.html.twig
<div class="frame">
    <p>
        <span class="bold">{{ show.title }}</span><br/>
        {{ show.summary }}<br/>
        <a class="show_link" href="{{ path('show', {'slug': show.slug}) }}">Lire la suite</a>
    </p>
    <div class="clear"></div>
</div>

src/LesAutres/SiteBundle/Resources/views/Default/sitemap.xml.twig
<?xml version="1.0" encoding="UTF-8"?>
<urlset
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"
>
{% for url in urls %}
    <url>
        <loc>{{ url }}</loc>
    </url>
{% endfor %}
</urlset>

src/LesAutres/SiteBundle/Resources/views/Default/slideshow.html.twig
{% set count = 1 %}
{% for image in images %}
    <img src="{{ web_dir }}/{{ image }}" alt="Image diaporama {{ count }}" width="250" height="375" id="slideshow_img_{{ count }}" />
    {% set count = count + 1 %}
{% endfor %}

src/LesAutres/SiteBundle/Resources/views/Default/social.html.twig
<div class="social">
    
    <!-- Facebook -->
    <iframe seamless width="100" height="21" src="https://www.facebook.com/plugins/like.php?href={{ url }}&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=21" title="Partager sur Facebook"></iframe>
    
    <!-- Twitter -->
    <iframe seamless width="100" height="21" src="https://platform.twitter.com/widgets/tweet_button.html?url={{ url }}&amp;via=la%20Compagnie%20des%20Autres" title="Partager sur Twitter"></iframe>
    
    <!-- Google + -->
    <iframe seamless width="100" height="21" src="https://plusone.google.com/_/+1/fastbutton?bsv&amp;size=medium&amp;hl=en-US&amp;url={{ url }}&amp;parent={{ url }}" title="Partager sur Google +"></iframe>
    
</div>

src/LesAutres/SiteBundle/Resources/views/Default/string.html.twig
{{ string }}